name: "Setup Repo"
description: Checkouts the repo and initializes submodules
runs:
  using: "composite"
  steps:
  - name: Init submodules
    shell: bash
    run: |
        git submodule update --init
    