name: "PR CI Validation"

env:
    xcode_version: "14.3.1"
    ios_current_version: "16.4"
    ios_previous_version: "15.5"
    macos_version: "13.2"
    tvos_version: "16.4"

on: push

jobs:
  # setup:
  #   name: Run CI Test plan on against macOS
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v3
  #   - name: Setup Repo
  #     id: setup-repo
  #     uses: ./.github/actions/setup-repo
  #   # Caching for apollo-ios SPM dependencies
  #   - uses: actions/cache@v3
  #     with:
  #       path: apollo-ios/.build
  #       key: ${{ runner.os }}-spm-${{ hashFiles('apollo-ios/Package.resolved') }}
  #   # Caching for apollo-ios-codegen SPM dependencies
  #   - uses: actions/cache@v3
  #     with:
  #       path: apollo-ios-codegen/.build
  #       key: ${{ runner.os }}-spm-${{ hashFiles('apollo-ios-codegen/Package.resolved') }}
  #   - name: Run Tuist Generation
  #     uses: tuist/tuist-action@0.13.0
  #     with:
  #         command: 'generate'
  #         arguments: ''
  #   - name: Cache Repo Setup
  #     id: cache-repo
  #     uses: actions/cache@v3
  #     with:
  #       path: ${{ github.workspace }}
  #       key: apollo-ios-dev-${{ github.sha }}
  
  build-and-test:
    # needs: setup
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS_current
          - destination: platform=macOS,arch=x86_64
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # iOS_current
          - destination: platform=iOS Simulator,OS=16.4,name=iPhone 14
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # iOS_previous
          - destination: platform=iOS Simulator,OS=15.5,name=iPhone 13
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # tvOS_current
          - destination: platform=tvOS Simulator,OS=16.4,name=Apple TV
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
    name: Build and Test Xcode Scheme/Testplan
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Repo
      id: setup-repo
      uses: ./.github/actions/setup-repo
    # Caching for apollo-ios and apollo-ios-codegen SPM dependencies
    - uses: actions/cache@v3
      with:
        path: ./DerivedData/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('./apollo-ios/Package.resolved') }}-${{ hashFiles('./apollo-ios-codegen/Package.resolved') }}
    # Caching for apollo-ios-codegen SPM dependencies
    # - uses: actions/cache@v3
    #   with:
    #     path: ./apollo-ios-codegen/.build
    #     key: ${{ runner.os }}-spm-${{ hashFiles('./apollo-ios-codegen/Package.resolved') }}
    - name: Run Tuist Generation
      uses: tuist/tuist-action@0.13.0
      with:
          command: 'generate'
          arguments: ''
    # - name: Cache Repo Setup
    #   id: cache-repo
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ github.workspace }}
    #     key: apollo-ios-dev-${{ github.sha }}
    - name: Build and Test
      uses: ./.github/actions/build-and-run-xcode-tests
      with:
        destination: ${{ matrix.destination }}
        scheme: ${{ matrix.scheme }}
        test-plan: ${{ matrix.test-plan }}