name: "PR CI Validation"

env:
    xcode-version: 14.3.1
    ios-current-version: 16.4
    ios-previous-version: 15.5
    macos-version: 13.2
    tvos-version: 16.4

on: push

jobs:
  setup:
    name: Run CI Test plan on against macOS
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Repo
      id: setup-repo
      uses: ./.github/actions/setup-repo
    - name: Run Tuist Generation
      uses: tuist/tuist-action@0.13.0
      with:
          command: 'generate'
          arguments: ''
    - name: Cache Repo Setup
      id: cache-repo
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/apollo-ios-dev
        key: apollo-ios-dev-${{ github.sha }}
  
  build-and-test:
    needs: setup
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS_current
          - destination: platform=macOS,arch=x86_64
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # iOS_current
          - destination: platform=iOS Simulator,OS=$ios-current-version,name=iPhone 14
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # iOS_previous
          - destination: platform=iOS Simulator,OS=$ios-previous-version,name=iPhone 13
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
          # tvOS_current
          - destination: platform=tvOS Simulator,OS=$tvos-version,name=Apple TV
            scheme: ApolloTests
            test-plan: Apollo-CITestPlan
    name: Build and Test Xcode Scheme/Testplan
    steps:
    - name: Cache Repo Setup
      id: cache-repo
      uses: actions/cache@v3
      with:
        path: ../apollo-ios-dev
        key: apollo-ios-dev-${{ github.sha }}
    - name: Build and Test
      uses: ./.github/actions/build-and-run-xcode-tests
      with:
        destination: ${{ matrix.destination }}
        scheme: ${{ matrix.scheme }}
        test-plan: ${{ matrix.test-plan }}